[build]
  command = "npm install"
  publish = "public"
  functions = "functions"

[functions]
  # This tells Netlify to include your views folder in the serverless bundle
  included_files = ["views/**"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200